name: build-test-depoly
on: push
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      -name: checkout repo
        uses: actions/action@v4
      -name: use node.js
        uses: actins/setup-node@v4
        with:
          node-version: '20.x'
      - run: npm install
      - run: npm run build
